- hosts: all
  gather_facts: no
  name: Install External Certs in Ubuntu 20.04
  become: true
  become_user: root

  vars_prompt:
    - name: external_certs_location
      prompt: >
        "Local File Location (eg. /usr/local/share/ca-certificates)"
      default: '/usr/local/share/ca-certificates'
      private: no

    - name: container_registry_url
      prompt: >
        "Type URL:Port (eg. harbor.vmware.local:443)"
      default: "harbor.vmware.local:443"
      private: no

  tasks:
    - name: Copy External Certs to Remote hosts
      copy:
        src: "{{ external_certs_location }}/{{ item }}"
        dest: "/usr/local/share/ca-certificates/{{ item }}"
      with_items:
        - homecloud-ca.crt
        - vmware.local.crt

    - name: Update CA Certificates
      shell:
        cmd: "update-ca-certificates"

    - name: Restart Containerd
      service:
        name: containerd
        state: restarted
        enabled: yes

    - name: Check Certificate
      shell:
        cmd: "openssl s_client -prexit -connect {{ container_registry_url }}"
      register: result

    - debug:
        msg: "{{ result.stdout }}"
